### ISSUE TITLE
Engineer - Readme & Contribution Guidelines - Unify Naming Conventions

### ISSUE THREAD

**Issue by stuartjohnpage** [revelrylabs/text_chunker_ex#7]
## Background
Standardize naming conventions both in Text Chunker's readme and codebase

### Scenario: Consistent Naming Convention Across Documentation and Codebase
- Given there are inconsistencies in naming within the readme and codebase, using both `Chunker` and `TextChunker`
- When documenting and referring to the library in the readme
- And when instances in the code, such as comments and documentation annotations, reference the library
- Then ensure all mentions align with a single, consistent naming convention, preferring `TextChunker`
- And correct all code comments, documentation strings, and annotations to consistently use `TextChunker`.

 _created by stuart.page+prodops1@revelry.co using [Prodops](https://app.prodops.ai)_

**Comment by stuartjohnpage** [comment]
looks like this is addressed by #8

**Comment by lukeledet** [comment]
merged #8
